language: node_js
node_js:
  - "8"
install:
  - yarn
cache:
  directories:
    - "node_modules"
before_deploy:
  - yarn build
deploy:
  provider: pages
  keep-history: true
  skip_cleanup: true
  committer_from_gh: true
  github_token: $GH_TOKEN
  verbose: true
  local_dir: build